### ISSUE TITLE
Estructura del modulo de Paciente

### ISSUE THREAD

**Issue by BerthaBrenes** [BerthaBrenes/HospitalTecnologico-frontend#1]
Crear un branch especifico para esta tarea

**Comment by Kstro379** [comment]
Se crean las vistas: Historial clínico y Gestión de reservaciones.

- 28/07/20. Duración: 5h.

**Comment by Kstro379** [comment]
Se crea la vista evaluaciones

* 04/08/2020. Duración 4h.
