### ISSUE TITLE
Estructura del modulo de Doctor

### ISSUE THREAD

**Issue by BerthaBrenes** [BerthaBrenes/HospitalTecnologico-frontend#2]
-Crear un branch especifico para esta tarea
-Crear las paginas/servicios y Componentes necesarios

**Comment by Kstro379** [comment]
* Se completa la vista del historial médico del paciente
* Se añade la estructura de navegabilidad de la misma
* 5 h.

**Comment by Kstro379** [comment]
- Creación de la página crear paciente.
- 27/07/20: 2h.
- 26/07/20: 2h.
